ELB_CROSS: "true"
INSTANCE_ROLE: "NOT_A_REAL_INSTANCE_ROLE"
KEY_NAME: "NOT_A_REAL_KEY_NAME"
PRIVATE_SUBNETS: "NOT_A_REAL_SUBNET_A,NOT_A_REAL_SUBNET_B"
PUBLIC_SUBNETS: "NOT_A_REAL_SUBNET_A,NOT_A_REAL_SUBNET_B"
SERVICE_ROLE: "NOT_A_REAL_SERVICE_ROLE"
SOLUTION_STACK: "64bit Amazon Linux 2016.09 v2.5.0 running Multi-container Docker 1.12.6 (Generic)"
VPC: "NOT_A_REAL_VPC"
